### ISSUE TITLE
Installathon

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#10]
We are running an installathon session on 12th of October @Diamond

Please try to be there (confirm here your attendance)

**Comment by pawlean** [comment]
I can't attend, unfortunately :( I'll be working at Uni of Sheff Enterprise (USE) that evening but good luck! Really sorry for lack of attendance lately!

**Comment by darrenvong** [comment]
Count me in! 🙋

**Comment by trallard** [comment]
Note this was moved to the 17th of October 5 - 6:30 pm
