### ISSUE TITLE
Sticky notes for on the fly feedback

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#12]
On previous programming courses with my team we have used a 'sticky note' approach to identify those attendees that need help with something. 

At the beginning of the course we give them two sticky notes (e.g. one green one red) and ask them to use them as follow:  stick the green on to of their laptop if everything is ok and they have completed the 'assigned task'  stick the red if they need help/are stuck. That way the instructors acting as helpers know who to help without distracting the main instructor or the class. Also if most of the girls are struggling the main instructor would be able to see this and allow for extra time, clarification, slowing down... etc

Thoughts????

**Comment by pawlean** [comment]
I think that this is such a great idea, it really helps with the management of time during the class. We should definitely make this happen!

**Comment by darrenvong** [comment]
What @paulienuh said after I read this! This should help to make it obvious when the girls are struggling on a particular topic as they'd probably start writing similar/the same things on their red sticky notes. Love it!

**Comment by pawlean** [comment]
Pink sticky note feedback from session 1 ![img_6173](https://user-images.githubusercontent.com/17087373/32142321-02dbdb40-bc8d-11e7-8d23-7a0d73e4d9af.JPG)

Green sticky notes feedback from session 2 
![img_6137](https://user-images.githubusercontent.com/17087373/32142326-15e624fc-bc8d-11e7-845c-3a9066f2d81c.JPG)

**Comment by darrenvong** [comment]
@paulienuh Were there any pink sticky notes feedback from session 2 too (even though we all knew @cgmcintyr was 🔥 with his delivery) 😃?

**Comment by darrenvong** [comment]
Sticky notes feedback from session 5!
![20171115_200946](https://user-images.githubusercontent.com/13669362/33013040-86a40d5e-cdda-11e7-96ef-7e658a721109.jpg)
