### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by pawlean** [trallard/Shef_CodeFirst_Python#13]
Booked pizza at Interval Bar on the 7th of November. ♥️ This can be changed but Lakshika and I agreed this would be a better date!

**Comment by darrenvong** [comment]
Can't see any issues with the date myself as long it's like late-ish (from 6.30pm onwards) so I don't have to rush from work, fail miserably at doing so and be like an hour late 😳

**Comment by pawlean** [comment]
Changed the date to the 31st of October, Interval from 8 onwards!
