### ISSUE TITLE
Need bios

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#14]
Could you please write down here a mini bio of your self for me to put in our site 😄 ???
It should contain:
- Name
- Title
- Small bio /text about you
- social media you want to add (Twitter, GitHub, linkedin, blog ...)

Just add it as a comment here 

Also if you have a picture of yourself add it to the repo please!

**Comment by pawlean** [comment]
Which site is this @trallard?

**Comment by trallard** [comment]
Since I made the template for the slides to be served online I though I would add a simple landing page with the link to the slides, the materials, etc etc

**Comment by trallard** [comment]
Since I made the template for the slides to be served online I though I would add a simple landing page with the link to the slides, the materials, etc etc

**Comment by pawlean** [comment]
I sent this to you T!

**Comment by cgmcintyr** [comment]
**Name:** Christopher McIntyre
**Title:** Python instructor
**About:** 3rd year Computer Science student. Linux and FOSS nerd 🐧
**Twitter:** @cgmcintyr

**Comment by ninas-sf** [comment]
Name: Nina Swanwick
Title: Junior Python instructor
About: Platform Manager for Aviva - Started 20+ years ago in IT, after a Computer Science HND as a coder in RPG on the I series platform, I also studied C++, BBC Basic, Comal, Cobal and some VB. 
Twitter: @ViolentNinaRossi
