### ISSUE TITLE
Instructors... are you missing any sessions???

### ISSUE THREAD

**Issue by trallard** [trallard/Shef_CodeFirst_Python#2]
uick git sheetPlease indicate if you won't be able to make any of the sessions.

Make sure to comment with your name and dates 😄

**Comment by pawlean** [comment]
Not an instructor but I thought I'd mention that I'll be missing 15th of November because https://twitter.com/paulienuh/status/915652882556506112 #livingmybestlife

**Comment by ninas-sf** [comment]
Will be missing 2nd session on 25th Oct as I'm on holiday fr the school half term
Nina
