### ISSUE TITLE
Talks

### ISSUE THREAD

**Issue by pawlean** [trallard/Shef_CodeFirst_Python#7]
Hi everyone, 

I'd like to invite some quick talks to the classes. I know you'd rather crack on with the lessons but to switch it up a bit I think having talks once in a while would be good.

### Some suggestions:

- MedTech - To see what they can do with their skills that would impact the "real world"
- HackSheffield - To empower them to attend some hackathons and apply their skills!
- Start-Up Weekend (Someone from USE has approached me to ask if this can be organised before their next start-up weekend event in November either 1st or 8th of November!)

### Confirmed:
- 8th of November: Start-Up Weekend

**Comment by darrenvong** [comment]
After our planning meeting yesterday, we have agreed that due to how little time we have, it is best to have a maximum of two talks with each of them not lasting longer than 15 minutes. @lj1396 had been taking minutes so there may be more info on that.

As a stretch goal, can we somehow get the other Tania (from Leeds) in to do one of the talks? Clearly not fan-boying as she liked my Heroku app example last semester 😆

**Comment by pawlean** [comment]
Thanks @darrenvong! :) Noted. I'll get in touch with Tanja!

**Comment by trallard** [comment]
I think we will have to revisit this later as we need to ensure we have enough time to cover all the materials

**Comment by pawlean** [comment]
Tanja is travelling so may not be able to. @darrenvong 

Can we organise StartUp Weekend to come in? I think it's good to get them to understand the applications of their new knowledge! :)

**Comment by darrenvong** [comment]
Ahh never mind, maybe next semester then. StartUp Weekend sounds good to me as an alternative!

**Comment by pawlean** [comment]
StartUp Weekend is on the 18th of November so perhaps the class before then? 8th of November? :)

**Comment by darrenvong** [comment]
If I am not mistaken, is that session 4? If so I'm OK with that as hopefully we've got a head start on Flask before then in session 3!

**Comment by pawlean** [comment]
Just an FYI - 8th of November - Christina Elliot from Start-Up weekend!

**Comment by darrenvong** [comment]
@paulienuh I know we are a little short on time... but out of curiosity, do we still have another one coming up?
