### ISSUE TITLE
Collecting projects

### ISSUE THREAD

**Issue by pawlean** [trallard/Shef_CodeFirst_Python#8]
This process needs to be done better this year because we have the ShefCodeFirst.com that showcases all of the previous work. _Any suggestions on how we can improve this?_ The only thing I can think of is mentioning the project early on and making it an objective during a session to deploy their apps etc. onto Heroku.

**Comment by trallard** [comment]
As discussed on the meeting the following tasks need to be completed:

- [x] get the girls to make teams and think of their project early on (session 2/3)
- [x] make sure that they are aware of the requirements of the project:
     -  at least one HTML template
     -  at least one python script (with functions)
     - the use of APIs **is not compulsory**
- [x] the goal of  session 6 (Heroku) is to get them to deploy a minimal example or at least their own project repo, that way they will be able o build and debug on that for the competition

**Comment by trallard** [comment]
@darrenvong  have you started drafting session '6' Now 7???

**Comment by darrenvong** [comment]
Not started the slides yet... but the step-by-step instructions I wrote from last time should give me a good enough headstart!

**Comment by pawlean** [comment]
Done this well this term but can be improved for next term. The aim is to try and get everyone deployed EARLY.
