### ISSUE TITLE
Introduction email

### ISSUE THREAD

**Issue by darrenvong** [trallard/Shef_CodeFirst_Python#9]
Due to the limited time we have to cover so much content, we thought that it may be a good idea to mention in the intro/welcome email to the girls that they should do the exercises up to a certain chapter in the [LPTHW e-book](https://learnpythonthehardway.org/python3/) before the first session.

I'll have a look through and decide what that certain chapter should be soon!

**Comment by pawlean** [comment]
Consider it done!

**Comment by darrenvong** [comment]
So having had a quick read through... it looks like the e-book may no longer be free. It's now only available as a preview up to Chapter 8, so maybe it's worth telling people to read up to that and we'll just have to cover the rest from there.

**Comment by trallard** [comment]
Also we need to mention that we have a **session 0 ** (Installathon)
They do not have to be there for the whole duration of the session but need to make sure to drop by at some point to get everything installed and ready for the course.

This will ensure most of it will run smoothly

**Comment by pawlean** [comment]
I'll work with @lj1396 on putting together an email and I'll send it to you all before I send it out :)

**Comment by darrenvong** [comment]
^ Sorry about that. Should never touch the GitHub website again on mobile... 😶
